"""Generate data/semantic/semantic_layer.yaml from the dbt Semantic Layer + warehouse catalog.

Single source of truth, two inputs merged:
  dbt/models/marts/_semantic_models.yml  -> grain, keys, measures (additivity), dimensions, joins
                                            (the standard dbt Semantic Layer / MetricFlow YAML)
  dbt/target/catalog.json                -> full column list + warehouse types
                                            (run: dbt compile --write-catalog)

Roles are read from the Semantic Layer: primary entity -> is_pk + grain; foreign entity ->
is_fk + a join path (matched to the dim that owns that entity as primary); measure -> is_measure;
everything else -> is_dimension. Output is a GENERATED artifact — never hand-edit it; edit the
dbt Semantic Layer YAML instead. Run via `make semantic`.

Usage:
  python scripts/generate_semantic_layer.py            # write semantic_layer.yaml
  python scripts/generate_semantic_layer.py --check    # exit 1 if the committed file is stale (CI gate)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "dbt" / "target" / "catalog.json"
SEM_MODELS = ROOT / "dbt" / "models" / "marts" / "_semantic_models.yml"
OUTPUT = ROOT / "data" / "semantic" / "semantic_layer.yaml"

_REF = re.compile(r"ref\(\s*'([^']+)'\s*\)")
_HEADER = (
    "# GENERATED by `make semantic` (scripts/generate_semantic_layer.py) -- DO NOT EDIT.\n"
    "# Columns + types come from the dbt warehouse catalog; grain, keys, measures, dimensions\n"
    "# and joins come from the dbt Semantic Layer (dbt/models/marts/_semantic_models.yml).\n"
    "# Edit those sources and regenerate; CI fails if this file drifts.\n"
)


def _model_name(unique_id: str) -> str:
    return unique_id.split(".")[-1]


def _expr(item: dict[str, Any]) -> str:
    """A semantic-layer item's column expression (defaults to its name), lower-cased."""
    return str(item.get("expr", item["name"])).lower()


def _catalog_columns(catalog: dict[str, Any], model: str) -> list[tuple[str, str]]:
    """(name, type) pairs for a model, lower-cased, in warehouse column order."""
    node = next((n for uid, n in catalog["nodes"].items() if _model_name(uid) == model), None)
    if node is None:
        raise SystemExit(f"model {model!r} not in catalog.json — run `dbt compile --write-catalog`")
    cols = sorted(node["columns"].values(), key=lambda c: c.get("index", 0))
    return [(c["name"].lower(), str(c["type"]).lower()) for c in cols]


def build() -> dict[str, Any]:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    sem = yaml.safe_load(SEM_MODELS.read_text(encoding="utf-8"))["semantic_models"]

    # model table name <- ref('...'); primary-entity index for join resolution.
    table_of = {sm["name"]: _REF.search(sm["model"]).group(1).lower() for sm in sem}  # type: ignore[union-attr]
    primary_of: dict[str, tuple[str, str]] = {}  # entity_name -> (table, column)
    for sm in sem:
        for e in sm.get("entities", []):
            if e["type"] == "primary":
                primary_of[e["name"]] = (table_of[sm["name"]], _expr(e))

    tables: list[dict[str, Any]] = []
    joinable: list[str] = []
    for sm in sem:
        table = table_of[sm["name"]]
        prim = next((e for e in sm.get("entities", []) if e["type"] == "primary"), None)
        foreign = [e for e in sm.get("entities", []) if e["type"] == "foreign"]
        pk_cols = {_expr(prim)} if prim else set()
        fk_map = {_expr(e): primary_of.get(e["name"]) for e in foreign}
        measure_cols = {_expr(m): m for m in sm.get("measures", [])}
        desc = {}
        for d in sm.get("dimensions", []):
            desc[_expr(d)] = d.get("description", "")
        for m in sm.get("measures", []):
            desc[_expr(m)] = m.get("description", "")

        columns: list[dict[str, Any]] = []
        for name, ctype in _catalog_columns(catalog, table):
            col: dict[str, Any] = {"name": name, "type": ctype}
            ref = fk_map.get(name)
            if name in pk_cols:
                col.update(description=desc.get(name, "Primary key."), is_pk=True)
            elif ref:
                col.update(description=f"Foreign key to {ref[0]}.{ref[1]}.", is_fk=True)
            elif name in measure_cols:
                col.update(description=desc.get(name, ""), is_measure=True)
            else:
                col.update(description=desc.get(name, ""), is_dimension=True)
            columns.append(col)

        fks = [
            {"column": col, "references": f"{ref[0]}.{ref[1]}"}
            for col, ref in fk_map.items()
            if ref
        ]
        tables.append(
            {
                "name": table,
                "grain": f"one row per {prim['name'].replace('_', ' ')}" if prim else "",
                "description": sm.get("description", ""),
                "primary_key": sorted(pk_cols),
                "foreign_keys": fks,
                "columns": columns,
            }
        )
        joinable.extend(f"{table}.{fk['column']} = {fk['references']}" for fk in fks)

    return {"tables": tables, "joinable_paths": joinable}


def render(doc: dict[str, Any]) -> str:
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, allow_unicode=True, width=120)
    return _HEADER + body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale (CI gate)")
    args = ap.parse_args()

    text = render(build())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("semantic_layer.yaml is STALE — run `make semantic` and commit.", file=sys.stderr)
            sys.exit(1)
        print("semantic_layer.yaml is up to date.")
        return
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
